#4 실습 (Assignment 6)

* 행렬방정식 풀기 (단, pytorch,만을 사용한다.)
  + 다음 행렬 방정식을 'Pseudo inverse matrix'를 이용해 풀어보자
  + $A^TA$의 역행렬이 존재한다고 가정

  $Ax=B$

  $A=\begin{bmatrix}0&1\\1&1\\2&1\\3&1\\ \end{bmatrix}$  
  $B=\begin{bmatrix}-1\\0.2\\0.9\\2.1\\ \end{bmatrix}$

---
* Pseudo Inverse matrix  

  $A^+=(A^TA)^{-1}A^T$  
  $x=A^+B$

In [ ]:
import numpy as np
import torch

#행렬 A를 선언 및 출력한다.
A_mat=torch.FloatTensor([[0, 1],[1, 1],[2, 1],[3, 1]])
print('A=')
print(A_mat)

#행렬 B를 선언 및 출력한다.
B_mat=torch.FloatTensor([[-1],[0.2],[0.9],[2.1]])
print('B='),
print(B_mat)

#A의 유사역행렬을 위의 공식을 통해 계산한다.
pseudo_inv_A_mat=torch.matmul(torch.inverse(torch.matmul(A_mat.T,A_mat)),A_mat.T)
print('Pseudo Inverse A=')
print(pseudo_inv_A_mat)

#유사역행렬을 통해 행렬 x를 구한다.
x_mat=np.dot(pseudo_inv_A_mat,B_mat)
print('x='),
print(x_mat)

A=
tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
B=
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])
Pseudo Inverse A=
tensor([[-0.3000, -0.1000,  0.1000,  0.3000],
        [ 0.7000,  0.4000,  0.1000, -0.2000]])
x=
[[ 1.0000002 ]
 [-0.95000035]]
