#실험 2 예비보고서

***
###1. 실험제목
#### PyTorch 를 사용한 Tensor 기초
###2.개요  
PyTorch 와 Tensor의 개념을 이해하고 Tensor의 활용 및 연산을 숙지한다.

###3.이론  
* Pytorch  

Python을 위한 오픈소스 머신 러닝 라이브러리이며, 자연어 처리를 위한 애플리캐이션 사용을 위해 사용한다. GPU사용이 가능하다는 장점을 가지고 있다.   
밑과 같이 imports 하여 사용한다.

In [3]:
import numpy as np
import torch

* Tensor  

1차원의 vector, 2차원의 matrix 를 넘어 그 이상의 n-차원의 배열들을 Tensor라 한다.  

* Rank  
Tensor의 차원의 개수를 rank라 한다.
  + Rank = 1 $\begin{bmatrix}1&2\\ \end{bmatrix}$
  + Rank = 2 $\begin{bmatrix}1&2\\3&4\\ \end{bmatrix}$

* Axis
위의 Rank가 차원의 개수를 의미했다면 Axis 는 n-차원에서의 특정한 차원을 의미한다. 가장 범주가 큰 차원일때 Axis = 0 이며 차원이 내려갈수록 Axis는 1씩 증가한다.  

* Shape  
한 차원의 요소의 개수들을 의미한다. 

In [8]:
tensor = torch.FloatTensor([[1, 2, 3, 4],[5, 6, 7, 8]])
print(tensor)
print(tensor.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])


### Tensor Combinations

* Concatenation  
경계를 무너뜨리며 Tensor를 이어붙이며 붙일 Axis를 정할 수 있고 rank는 변하지 않는다.
* Stack 
경계를 구분한 채로 붙이며 Axis를 정할 수 있고 rank는 변한다.

In [9]:
x = torch.FloatTensor([[2, 3], [4, 5]])
y = torch.FloatTensor([[6, 7], [8, 9]])
print(x)
print(y)
print(torch.cat([x,y], dim = 1))
print(torch.stack([x,y], dim = 1))

tensor([[2., 3.],
        [4., 5.]])
tensor([[6., 7.],
        [8., 9.]])
tensor([[2., 3., 6., 7.],
        [4., 5., 8., 9.]])
tensor([[[2., 3.],
         [6., 7.]],

        [[4., 5.],
         [8., 9.]]])


* View / Reshape  
data를 유지한채 shape을 변형한다. 주의점으로는 Pointer를 반환하기에 원본이 훼손되지 않도록 복사본을 이용한다.

In [10]:
x = torch.FloatTensor([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]]) # [2, 2, 3]
y = x.view(2, -1)  # [2, 6] 
z = x.reshape(2, -1) # [2, 6]
print(x)
print(y)
print(z)
z[0] = 0.0
#원본이 훼손되어 출력
print(x)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])
tensor([[[ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


* Squeeze  
불필요한 rank를 줄인다

In [15]:
x = torch.FloatTensor([[1, 2, 3]])
print(x)
print(x.T)
print(x.T.squeeze())

tensor([[1., 2., 3.]])
tensor([[1.],
        [2.],
        [3.]])
tensor([1., 2., 3.])


### Tensor Operations

* 요소별 곱셉 및 덧셈

In [26]:
x = torch.FloatTensor([1, 2, 3])
y = torch.FloatTensor([[1, 2, 3],[4, 5, 6]])
print(x)
print(y)
#요소별 곱셉
print(x * y)
#요소별 덧셈
print(x + 2)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 1.,  4.,  9.],
        [ 4., 10., 18.]])
tensor([3., 4., 5.])


* 전치행렬, 행렬곱, 역행렬

In [23]:
#전치행렬
print(y)
print(y.T)
#행렬곱
print(x)
print(y.matmul(x))
#역행렬
z = torch.FloatTensor([[3, 4], [-4, 5]]) 
print(torch.inverse(z))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([1., 2., 3.])
tensor([14., 32.])
tensor([[ 0.1613, -0.1290],
        [ 0.1290,  0.0968]])


* Mean, Sum, Max

In [28]:
print(y)
# 요소들의 평균값
print(y.mean())
# 요소들의 합
print(y.sum())
# 요소들의 최대값
print(y.max())


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(3.5000)
tensor(21.)
tensor(6.)


###4.실습 과정    
강의 [Notebook](https://github.com/chorok-daddy/courses/blob/main/ML_Exp/EX2_Tensor_Manipulation.ipynb)(EX2)의 실습 부분을 직접 타이핑하며 진행한다.