#실험 4 결과보고서

***

In [1]:
import numpy as np 
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt

# seed 고정
torch.manual_seed(1)

In [2]:
#(6,2) 크기의 x_tain 설정
x_train = torch.FloatTensor([[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]])
#(6,1) 크기의 y_tain 설정
y_train = torch.FloatTensor([[0],[0],[0],[1],[1],[1]])

#x_train 및 x_train의 shape 출력
print(x_train)
print(x_train.shape)
#y_train 및 y_train의 shape 출력
print(y_train)
print(y_train.shape)

#Logistic 함수의 설정 
class Logistic(nn.Module):

  
  #__init__의 정의
  def __init__(self,num_inputs, num_outputs):
    #자식 클래스의 초기화 메서드에서 부모 클래스의 초기화 메서드를 호출위한 코드
    super().__init__()
    #self.linear는 Linear Regression으로 model을 만들어줌
    self.linear = nn.Linear(num_inputs, num_outputs)
    #self.sigmoid란 Sigmoid 모델을 만들어준다.
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    #sigmoid(linear(x))의 형태로 모델을 만들어준다
    return self.sigmoid(self.linear(x))

#input = 2 , output=1 임을 확인 
model = Logistic(2,1)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
torch.Size([6, 2])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
torch.Size([6, 1])


In [3]:
#learnig rate를 1로 설정
optimizer = opt.SGD(model.parameters(),lr=1)

#gradient descent를 100번 실행
for epoch in range(100):

  #y_hypo를 sidmoid 모델의 변수들로 설정
  y_hypo = model(x_train)
  #cost 를 binary cross entropy로 설정
  cost = func.binary_cross_entropy(y_hypo, y_train)

  #gradient descent 실행
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #10번마다 출력
  if epoch % 10 == 9:

    #prediction이 0.5 이상이면 1를 반환하도록 설정
    prediction = y_hypo >= torch.FloatTensor([0.5])
    #prediction이 참인지 확인
    correct_prediction = prediction.float() == y_train
    #prediction의 참인 확률을 accuracy로 설정 
    accuracy = correct_prediction.sum().item()/len(correct_prediction)
    #cost,accuracy 출력
    #cost는 점점 줄어들고 accuracy 는 100%에 근사하는 것을 확인
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, 100, cost.item(), accuracy * 100,
    ))

print(y_hypo)



Epoch    9/100 Cost: 0.764956 Accuracy 66.67%
Epoch   19/100 Cost: 0.596826 Accuracy 83.33%
Epoch   29/100 Cost: 0.491604 Accuracy 83.33%
Epoch   39/100 Cost: 0.405330 Accuracy 83.33%
Epoch   49/100 Cost: 0.323565 Accuracy 83.33%
Epoch   59/100 Cost: 0.249201 Accuracy 83.33%
Epoch   69/100 Cost: 0.191438 Accuracy 100.00%
Epoch   79/100 Cost: 0.159492 Accuracy 100.00%
Epoch   89/100 Cost: 0.145180 Accuracy 100.00%
Epoch   99/100 Cost: 0.135187 Accuracy 100.00%
tensor([[0.0247],
        [0.1486],
        [0.2780],
        [0.7950],
        [0.9481],
        [0.9833]], grad_fn=<SigmoidBackward0>)


In [4]:
#CSV 파일로 부터 data를 가져옴, 크기는 (758,9)
dataset = np.loadtxt(
    '/content/drive/MyDrive/Colab Notebooks/data_logistic_regression.csv', 
    delimiter=',', 
    dtype=np.float32)

#x_train에 shape(758,8)의 data를 할당
x_train = torch.FloatTensor(dataset[:,:-1])
#y_train에 (758,1)의 data를 할당
y_train = torch.FloatTensor(dataset[:,[-1]])

#따라서 input은 8, output은 1 
model = Logistic(8,1)

#learnig rate를 3으로 설정
optimizer = opt.SGD(model.parameters(),lr=3)

for epoch in range(100):

  y_hypo = model(x_train)
  cost = func.binary_cross_entropy(y_hypo, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 10 == 9:
    
    #prediction이 0.4 이상이면 1를 반환하도록 설정
    prediction = y_hypo >= torch.FloatTensor([0.4])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item()/len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, 100, cost.item(), accuracy * 100,
    ))


Epoch    9/100 Cost: 0.517925 Accuracy 70.22%
Epoch   19/100 Cost: 0.491282 Accuracy 74.97%
Epoch   29/100 Cost: 0.481864 Accuracy 75.49%
Epoch   39/100 Cost: 0.477654 Accuracy 75.89%
Epoch   49/100 Cost: 0.475504 Accuracy 76.81%
Epoch   59/100 Cost: 0.474292 Accuracy 77.34%
Epoch   69/100 Cost: 0.473552 Accuracy 77.47%
Epoch   79/100 Cost: 0.473069 Accuracy 77.34%
Epoch   89/100 Cost: 0.472735 Accuracy 77.34%
Epoch   99/100 Cost: 0.472495 Accuracy 77.34%
