#실험 2 결과보고서

***

In [2]:
#numpy 와 torch 를 import 
import numpy as np
import torch

In [21]:
#tensor 를 torch.FloatTensor 코드를 이용해 생성
tensor = torch.FloatTensor([1,2,3,4])
#이후 print 함수로 tensor를 출력
print(tensor)
#.shape 함수를 이용해 tensor의 shape를 출력
#해당 tensor는 rank가 1이고 안의 데이터가 4개 있으므로 4가 출력됨
print(tensor.shape)
#이후 tensor의 1~4 번째의 데이터들을 출력 따라서 2,3,4가 출력됨
print(tensor[1:4])

tensor([1., 2., 3., 4.])
torch.Size([4])
tensor([2., 3., 4.])


In [19]:
#rank가 3이며 axis= 0 일때 2개 ,axis = 1 일때 3개 axis=3 일때 4개의 값을 갖는
tensor를 생성
tensor3d = torch.FloatTensor([[[6,2,3,4],
                               [5,6,7,8],
                               [9,10,11,12]],
                              [[13,14,15,16],
                               [17,18,19,20],
                               [21,22,23,24]]])
print(tensor3d)
#따라서 shape는 [2,3,4]가 출력
print(tensor3d.shape)

tensor([[[ 6.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
torch.Size([2, 3, 4])


In [10]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])
print(x)
print(y)
#torch.cat 함수를 통해 tensor를 결합함 
#cat 함수는 combination 할 tensor 와 , dim 의 값을 받아서 실행한다. 
#dim = 0 일때는 axis = 0 인 부분의 경계를 지우며 합쳐지도록 결합
print(torch.cat([x,y],dim=0))
#dim = 1 일때는 axis = 0 인 부분의 경계를 없에고 결합
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [11]:
#.stack 함수또한 tensor를 결합하나 .cat과는 달리 경계를 무너뜨리지 않는다.
#dim 의 값을 통해 결합하는 방향을 정할 수 있음 dim = 0 일때는 axis = 0 인 공간에
print(torch.stack([x,y], dim = 0)) 
#dim = 1 일때는 axis = 1 인 공간에 쌓는다.
print(torch.stack([x,y], dim = 1))

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])


In [ ]:
#torch.rand 코드를 통해 shape 가 (2,3,4) 인 tensor를 만들고 값을 랜덤으로 할당
x=torch.rand(2,3,4)
#view, reshpe 를 통해 tensor를 변형
#이때 component(-1) 값을 주었을 경우 자동으로 크기에 맞는 값이 할당 됨
y=x.view(2,-1) #(2,12)
z=x.reshape(2,-1) #(2,12)
print(x)
print(y)
print(z)
#이때 view, reshape 통해 만들어진 tensor는 기존의 tensor의 포인터를 반환하므로 원본이 훼손될 수 있음
#z[0]=0.0 코드 때문에 기존의 tensor가 x[0] 부분또한 0이 되는 걸 볼 수 있다.
z[0]=0.0
print(x)

In [16]:
#np.array 함수로 -data에 [1,2,3,4] 배열을 할당
_data=np.array([1,2,3,4])
x=torch.from_numpy(_data)
#x=torch.from_numpy(_data) 코드를 통해 tensor를 만들고 데이터를 입력 
#shape(4) 이므로 transpose 또한 동일함을 확인
print(x)
print(x.T)
#이후 shape(4,1)인 함수를 만들어주고 
_data=np.array([_data])
x=torch.from_numpy(_data)
print(x)
#이를 transpose 하여 shape(1,4) 인 tensor를 만들어 준다.
print(x.T)
#squeeze 함수는 차원이 1인 차원을 제거하므로
#shape(1,4) -> shape(4) 로 tensor는 변형된다
print(x.T.squeeze())

tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([1, 2, 3, 4])


$$
\begin{aligned}
A = 
\begin{bmatrix}a_{1}&a_{2}& \ldots &a_{n}\end{bmatrix}\\  
B= 
\begin{bmatrix}b_{1}&b_{2}& \ldots &b_{n}\end{bmatrix}\\
A*B = \begin{bmatrix}a_{1}*b_{1}&a_{2}*b_{2}& \ldots &a_{n}*b_{n}\end{bmatrix}\\
\end{aligned}
$$

In [22]:
print(tensor)
print(tensor3d)
#위 식에 따라 행렬이 합되는 것을 확인할 수 있다.
print(tensor*tensor3d)

tensor([1., 2., 3., 4.])
tensor([[[ 6.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([[[ 6.,  4.,  9., 16.],
         [ 5., 12., 21., 32.],
         [ 9., 20., 33., 48.]],

        [[13., 28., 45., 64.],
         [17., 36., 57., 80.],
         [21., 44., 69., 96.]]])


$$
\begin{aligned}
A = 
\begin{bmatrix}a_{1}&a_{2}& \ldots &a_{n}\end{bmatrix}\\  
A+3 =
\begin{bmatrix}a_{1}+3&a_{2}+3& \ldots &a_{n}+3\end{bmatrix}\\ 
\end{aligned}
$$

In [ ]:
#각 행에 상수항이 더해진다.
print(tensor3d+3)

tensor([[[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.],
         [24., 25., 26., 27.]]])


In [39]:
#shape(2,3,4)인 tensor가 동일하지 않은 shape를 가진 tensor와 add 할 경우 
#axis에 맞춰서 각 값들을 더 해주게 된다.
tensor_a=torch.FloatTensor([1,2,3,4])
tensor_b=torch.FloatTensor([[1],[2],[3]])
tensor_c=torch.FloatTensor([[[1]],[[2]]])
print(tensor3d)
#[6+1,2+2,3+3,4+4]
print(tensor3d+tensor_a) 
#[6+1,2+1,3+1,4+1]
#[5+2,6+2,7+2,8+2]
print(tensor3d+tensor_b)
#[6+1,2+1,3+1,4+1]
#[13+2,14+2,15+2,16+2]
print(tensor3d+tensor_c)

tensor([[[ 6.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor([6., 5., 9.])
tensor([[[ 7.,  4.,  6.,  8.],
         [ 6.,  8., 10., 12.],
         [10., 12., 14., 16.]],

        [[14., 16., 18., 20.],
         [18., 20., 22., 24.],
         [22., 24., 26., 28.]]])
tensor([[[ 7.,  3.,  4.,  5.],
         [ 7.,  8.,  9., 10.],
         [12., 13., 14., 15.]],

        [[14., 15., 16., 17.],
         [19., 20., 21., 22.],
         [24., 25., 26., 27.]]])
tensor([[[ 7.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9.],
         [10., 11., 12., 13.]],

        [[15., 16., 17., 18.],
         [19., 20., 21., 22.],
         [23., 24., 25., 26.]]])


In [ ]:
#.matmul() 함수를 통해 행렬곱을 계산할 수 있다.
print(tensor3d.matmul(tensor))

tensor([[ 30.,  70., 110.],
        [150., 190., 230.]])


'.mean',`.sum`,`max` 함수를 통해 평균값,합, 최소값을 계산한다..  
dim을 입력하지 않았을 때 전체 값을 계산하며,  
dim을 입력받았을 때는 ,dim의 값에 따라 각 축의 값들을 계산한다.

In [ ]:
print(tensor3d)
print(tensor3d.mean())
print(tensor3d.shape)
print(tensor3d.mean(dim=0))
print(tensor3d.mean(dim=1))
print(tensor3d.mean(dim=2))

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor(12.5000)
torch.Size([2, 3, 4])
tensor([[ 7.,  8.,  9., 10.],
        [11., 12., 13., 14.],
        [15., 16., 17., 18.]])
tensor([[ 5.,  6.,  7.,  8.],
        [17., 18., 19., 20.]])
tensor([[ 2.5000,  6.5000, 10.5000],
        [14.5000, 18.5000, 22.5000]])


In [24]:
print(tensor3d.sum())
print(tensor3d.sum(dim=0))
print(tensor3d.sum(dim=1))

tensor(305.)
tensor([[19., 16., 18., 20.],
        [22., 24., 26., 28.],
        [30., 32., 34., 36.]])
tensor([[20., 18., 21., 24.],
        [51., 54., 57., 60.]])


In [40]:
print(tensor3d) 
print(tensor3d.max()) 
print(tensor3d.max(dim=1)) 
values,indices=tensor3d.max(dim=1) 
print(values)

tensor([[[ 6.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])
tensor(24.)
torch.return_types.max(
values=tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]]),
indices=tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]]))
tensor([[ 9., 10., 11., 12.],
        [21., 22., 23., 24.]])


In [ ]:
tensor_square=torch.FloatTensor([[1,7],[-4,6]])
#torch.inverse() 함수를 통해 역행렬을 계산한다.
print(torch.inverse(tensor_square))

tensor([[ 0.1765, -0.2059],
        [ 0.1176,  0.0294]])


Ax=B 에서 A가 non-square 하므로 A의 역행렬을 구할 수 없다.  
따라서 A의 역행렬의 역할을 수행하는 행렬이 필요하며 이를 pseudo inverse라 한다. 이를 구하는 식은 다음과 같다.

$$
\begin{aligned}
Ax=B\\
A^+=(A^TA)^{-1}A^T\\
x=A^+B
\end{aligned}
$$

이를 활용하여 행렬방정식을 푼 결과는 다음과 같다.

In [3]:
A = torch.FloatTensor([[0, 1], [1, 1], [2,1],[3,1]])
B = torch.FloatTensor([[-1], [0.2], [0.9],[2.1]])
print(A)
print(B)


tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
tensor([[-1.0000],
        [ 0.2000],
        [ 0.9000],
        [ 2.1000]])


In [45]:
pse = torch.inverse(A.T.matmul(A)).matmul(A.T)
print(pse)
x=pse.matmul(B)
print(x)
print(A.matmul(x))

tensor([[-0.3000, -0.1000,  0.1000,  0.3000],
        [ 0.7000,  0.4000,  0.1000, -0.2000]])
tensor([[ 1.0000],
        [-0.9500]])
tensor([[-0.9500],
        [ 0.0500],
        [ 1.0500],
        [ 2.0500]])
